openai_model = "gpt-4o"

target_variable = 'Weekly Sales'
key_category = 'Store ID'

pred_var = "y (Total Weekly Sales Amount)"
forecast_disc = "forecastt_diff (Forecast Discrepancy in Total Weekly Sales Amount in both models)"

model_info = "MLForecast(models=[LGBMRegressor], freq=W, lag_features=['lag1', 'lag52', 'lag104', 'expanding_mean_lag3'], date_features=['year', <function week_of_month at 0x000001EB36568720>, <function week_of_year at 0x000001EB36569B20>], num_threads=1)"
model_hyperparams = "lgb.LGBMRegressor(random_state=0, num_leaves=512, verbosity=-1)"

model_info = model_info + "|" + model_info
model_hyperparams = model_hyperparams + "|" + model_hyperparams


# business_scenario = """Improving Retail Sales Forecast Accuracy
# A major retail chain operating 45 stores faces challenges in predicting and understanding their 12-week sales forecasts. Inaccurate predictions lead to stockouts, overstocking, and inefficient resource allocation, directly impacting revenue and customer satisfaction.

# Challenge:
# Store managers and executives need to understand why sales forecasts deviate from actuals. Current forecasting methods provide predictions but lack clear explanations for deviations, making it difficult to take corrective actions.

# Stakes:
# - Inventory costs from over/understocking
# - Staff scheduling inefficiencies
# - Missed sales opportunities
# - Suboptimal promotional timing
# - Resource misallocation across stores

# Solution:
# We're developing an automated analysis system that explains forecast deviations in business terms. Our system includes a comprehensive three-part analysis using an LGBM (Light Gradient Boosting Machine) model that not only predicts weekly sales but explains prediction patterns through:

# 1. Feature Impact Analysis:
#    - Examining historical sales patterns' impact on future predictions
#    - Quantifying promotional effectiveness across different store types
#    - Understanding seasonal and holiday effects on sales
#    - Measuring the relationship between store characteristics and sales performance

# 2. Performance Evaluation:
#    - Weekly tracking of forecast vs. actual sales
#    - Store-level performance analysis
#    - Statistical testing to validate findings
#    - Cost-benefit assessment of prediction risks

# 3. SHAP Value Analysis:
#    - Breaking down how each factor contributes to predictions
#    - Tracking changes in feature importance over time
#    - Identifying patterns in prediction deviations
#    - Creating monthly summaries of key influencing factors

# This helps:
# - Store managers adjust inventory based on forecast reliability
# - Operations teams optimize staffing levels
# - Marketing teams time promotions more effectively
# - Executives make data-driven resource allocation decisions

# Impact:
# Better forecast understanding leads to improved inventory management, optimized promotions, and more efficient resource allocation across stores.
# """

business_scenario = """Business Scenario:
A consultancy firm operating from multiple regions, each comprising several departments.
The revenue is generated by providing data science AI services to the clients. You are provided with the historical revenue data
to analyze performance across the regions to predict future revenue across the region accurately incorporating the current assosciated deals, 
pipeline deals, exteranl factors and holidays.
"""

# business_scenario = """Business Scenario:
#    A retail company operates 45 stores across multiple regions, each comprising several departments. 
#    Throughout the year, the company runs promotional markdown events, especially leading up to major holidays 
#    such as the Super Bowl, Labor Day, Thanksgiving, and Christmas. These holiday periods are critical for business 
#    performance. You are provided with historical sales data to analyze performance across stores, departments, and 
#    promotional events, with a focus on optimizing outcomes during high-impact holiday periods. 

# Solution Details:
#    The forecasting task was approached using the DemFore package, with the LightGBM (LGBM) model selected based on 
#    its superior performance over other evaluated models. To enhance model accuracy, highly correlated variables were 
#    removed to reduce multicollinearity, and lag features were engineered on the target variable. Additionally, 
#    performance was further improved through strategic preprocessing steps, including binning and outlier removal in the test data. 

# Expectations from the tool:
#    The analysis is structured around three main pillars: trendline insights, residual patterns, and model forecast 
#    discrepancies. Each section highlights the most impactful deviations observed in the top two stores, ensuring 
#    relevance and clarity for executive stakeholders. The report concludes with actionable recommendations aimed at 
#    enhancing forecasting accuracy and supporting data-driven decision-making across the retail chain's 45 stores.
# """
